# SH Color Theme Version 0.1
# BLACK GOLD

COLOR_BACKGROUND="#090502"
COLOR_FOREGROUND="#FFE9AD"

# BLACK
COLOR_BLACK_DARK="#372840"
COLOR_BLACK_LIGHT="#483454"

# RED
COLOR_RED_DARK="#F39241"
COLOR_RED_LIGHT="#F5A969"

# GREEN
COLOR_GREEN_DARK="#FFAE4D"
COLOR_GREEN_LIGHT="#FFAE4D"

# YELLOW
COLOR_YELLOW_DARK="#F39241"
COLOR_YELLOW_LIGHT="#F5A969"

# BLUE
COLOR_BLUE_DARK="#FFAE4D"
COLOR_BLUE_LIGHT="#FFAE4D"

# MAGENTA
COLOR_MAGENTA_DARK="#F6BA53"
COLOR_MAGENTA_LIGHT="#F6BA53"

# CYAN
COLOR_CYAN_DARK="#F6BA53"
COLOR_CYAN_LIGHT="#F6BA53"

# WHITE
COLOR_WHITE_DARK="#FFE9AD"
COLOR_WHITE_LIGHT="#FFF3D5"
