# SH Color Theme Version 0.1
# STEEL
# Blue gray

COLOR_BACKGROUND="#0D100E"
COLOR_FOREGROUND="#52685C"

# BLACK
COLOR_BLACK_DARK="#202924"
COLOR_BLACK_LIGHT=$COLOR_BLACK_DARK

# RED
COLOR_RED_DARK="#768b7d"
COLOR_RED_LIGHT=$COLOR_RED_DARK

# GREEN
COLOR_GREEN_DARK="#9baaa0"
COLOR_GREEN_LIGHT=$COLOR_GREEN_DARK

# YELLOW
COLOR_YELLOW_DARK=$COLOR_RED_DARK
COLOR_YELLOW_LIGHT=$COLOR_YELLOW_DARK

# BLUE
COLOR_BLUE_DARK=$COLOR_GREEN_DARK
COLOR_BLUE_LIGHT=$COLOR_BLUE_DARK

# MAGENTA
COLOR_MAGENTA_DARK="#768b7d"
COLOR_MAGENTA_LIGHT=$COLOR_MAGENTA_DARK

# CYAN
COLOR_CYAN_DARK=$COLOR_MAGENTA_DARK
COLOR_CYAN_LIGHT=$COLOR_CYAN_DARK

# WHITE
COLOR_WHITE_DARK=$COLOR_FOREGROUND
COLOR_WHITE_LIGHT="#FFFFFF"
