# SH Color Theme Version 0.1
# REDFALL

COLOR_BACKGROUND="#150405"
COLOR_FOREGROUND="#C12423"

# BLACK
COLOR_BLACK_DARK="#5B161C"
COLOR_BLACK_LIGHT=$COLOR_BLACK_DARK

# RED
COLOR_RED_DARK="#7D1A1E"
COLOR_RED_LIGHT=$COLOR_RED_DARK

# GREEN
COLOR_GREEN_DARK="#FC1919"
COLOR_GREEN_LIGHT=$COLOR_GREEN_DARK

# YELLOW
COLOR_YELLOW_DARK=$COLOR_RED_DARK
COLOR_YELLOW_LIGHT=$COLOR_YELLOW_DARK

# BLUE
COLOR_BLUE_DARK=$COLOR_GREEN_DARK
COLOR_BLUE_LIGHT=$COLOR_BLUE_DARK

# MAGENTA
COLOR_MAGENTA_DARK=$COLOR_BLACK_DARK
COLOR_MAGENTA_LIGHT=$COLOR_MAGENTA_DARK

# CYAN
COLOR_CYAN_DARK=$COLOR_FOREGROUND
COLOR_CYAN_LIGHT=$COLOR_CYAN_DARK

# WHITE
COLOR_WHITE_DARK="#FC1919"
COLOR_WHITE_LIGHT=$COLOR_WHITE_DARK
