#! /bin/sh

# xrandr --output DVI-D-1 --off
# xrandr --output DVI-I-1 --mode 1920x1200

bspc monitor DVI-D-1 -n L -d i ii iii
bspc monitor DVI-I-1 -n R -d I II III

bspc config top_padding         18
bspc config border_width        1
bspc config window_gap          12
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc config normal_border_color "#FFAE4D"
bspc config active_border_color "#FFAE4D"
bspc config focused_border_color "#FFAE4D"

# Kill panel and start
# if [ $(pgrep -f 'panel') ]; then
#     kill $(pgrep -f 'panel' | head -1)
# fi
panel &
