#! /bin/sh

bspc monitor -d I II III 

bspc rule -a Chromium -d ^2

bspc config top_padding         20
bspc config border_width        0
bspc config window_gap          12
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Kill panel and start
# if [ $(pgrep -f 'panel') ]; then
#     kill $(pgrep -f 'panel' | head -1)
# fi
panel &
