#! /bin/sh

source ~/.colors/current-sh

# Padding to force to center
bspc config top_padding 190
bspc config right_padding 430
bspc config bottom_padding 415
bspc config left_padding 430
bspc config border_width 1

# Normal Padding
# PADDING=40
# bspc config top_padding         58
# bspc config right_padding       $PADDING
# bspc config bottom_padding      $PADDING
# bspc config left_padding        $PADDING

bspc config window_gap          12
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# bspc config border_width        1
bspc config normal_border_color $COLOR_BACKGROUND 
bspc config active_border_color $COLOR_BACKGROUND
bspc config focused_border_color $COLOR_MAGENTA_DARK

bspc monitor DVI-D-0 -n ALPHA -d IV V VI
bspc monitor DVI-I-1 -n BETA -d I II III

# Kill panel and start
if [ $(pgrep 'panel') ]; then
    pgrep 'panel' | xargs kill -s 9
fi

# panel &
# info_panel.sh &

