#! /bin/sh
#
# BSPWM Desktop information for dzen2

# Import colors
. ~/.colors/current-sh

NORMIFS=$IFS
FIELDIFS=':'
PADDING='  '

while read -r line ; do
    case $line in
        S*)
            # clock output
            # sys_infos="^fg($COLOR_FOREGROUND)^bg($COLOR_BACKGROUND)${PADDING}${line#?}${PADDING}^fg()^bg()${PADDING}"
            ;;
        T*)
            # xtitle output
            # title="^fg($COLOR_FOREGROUND)^bg($COLOR_BACKGROUND)${PADDING}${line#?}${PADDING}^fg()^bg()"
            ;;
        W*)
            # bspwm internal state
            monitor="BETA"
            wm1_infos="$PADDING"
            wm2_infos="$PADDING"
            m_infos="$PADDING"
            IFS=$FIELDIFS
            set -- ${line#?}
            while [ $# -gt 0 ] ; do
                item=$1
                case $item in
                    [OoFfUu]*)
                        # desktops
                        name=${item#?}
                        case $item in
                            O*)
                                # focused & occupied desktop
                                FG=$COLOR_RED_DARK
                                ;;
                            F*)
                                # focused & free desktop
                                FG=$COLOR_RED_DARK
                                ;;
                            U*)
                                # focused & urgent desktop
                                FG=$COLOR_RED_DARK
                                ;;
                            o*)
                                # occupied desktop
                                FG=$COLOR_WHITE_DARK
                                ;;
                            f*)
                                # free desktop
                                FG=$COLOR_FOREGROUND
                                ;;
                            u*)
                                # urgent desktop
                                FG=$COLOR_BLUE_DARK
                                ;;
                        esac
                        BG=$COLOR_BACKGROUND
                        # Append to wm*_infos
                        if [ "$monitor" = 'BETA' ];
                        then
                            wm2_infos="${wm2_infos}^fg(${FG})^bg(${BG})${PADDING}-${PADDING}";
                            # wm2_infos="${wm2_infos}^fg(${FG})^bg(${BG})${PADDING}${name}${PADDING}";
                        else
                            wm1_infos="${wm1_infos}^fg(${FG})^bg(${BG})${PADDING}-${PADDING}";
                            # wm1_infos="${wm1_infos}^fg(${FG})^bg(${BG})${PADDING}${name}${PADDING}";
                        fi
                        ;;
                    L*)
                        # layout
                        # layout=$(printf "%s" "${item#?}" | sed 's/^\(.\).*/\U\1/')
                        # wm_infos="${wm_infos}^fg()^bg()${PADDING}${PADDING}^fg($COLOR_FOREGROUND)^bg($COLOR_BACKGROUND)${PADDING}$layout${PADDING}"
                        ;;
                    [Mm]*)
                        # Monitors
                        # m:active m:inactive
                        monitor=${item#?}
                        FG=$COLOR_FOREGROUND
                        BG=$COLOR_BACKGROUND
                        m_infos="${m_infos}^fg(${FG})^bg(${BG})${PADDING}${item#?}${PADDING}"
                        ;;
                esac
                shift
            done
            IFS=$NORMIFS
            ;;
    esac

    # Print for dzen2
    # format: leftwm_info : rightwm_info
    printf "^pa(10)%s" "$wm1_infos"
    printf ":"
    printf "^pa(10)%s" "$wm2_infos"
    printf "\n"
done
