#!/bin/bash

. ~/.colors/current-sh

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

# flavor=${1:-bar}
flavor=${1:-dzen2}

PANEL_HEIGHT=8

# bspc config top_padding $PANEL_HEIGHT
# bspc control --put-status
bspc control --subscribe > "$PANEL_FIFO" &
# xtitle -sf 'T%s' > "$PANEL_FIFO" &
# clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &

case "$flavor" in
    dzen2)
        FONT_FAMILY='lemon'
        FONT_SIZE=8
        cat "$PANEL_FIFO" | \
            panel_dzen2 -o 1920 -f "$FONT_FAMILY" -s "$FONT_SIZE" | \
            tee >(sh ~/.config/bspwm/panel/split_panel.sh 1 1920 0) | \
            sh ~/.config/bspwm/panel/split_panel.sh 2 120 1920
        ;;
esac

wait
