# SH Color Theme Version 0.1
# FORREST

COLOR_BACKGROUND="#3E454C"
COLOR_FOREGROUND="#FFF6E5"

# BLACK
COLOR_BLACK_DARK="#1D2024"
COLOR_BLACK_LIGHT="#2E3338"

# RED
COLOR_RED_DARK="#FF7F66"
COLOR_RED_LIGHT="#FF9682"

# GREEN
COLOR_GREEN_DARK="#2185c5"
COLOR_GREEN_LIGHT="#3FA6E8"

# YELLOW
COLOR_YELLOW_DARK="#FF7F66"
COLOR_YELLOW_LIGHT="#FF9682"

# BLUE
COLOR_BLUE_DARK="#2185c5"
COLOR_BLUE_LIGHT="#3FA6E8"

# MAGENTA
COLOR_MAGENTA_DARK="#7ecefd"
COLOR_MAGENTA_LIGHT="#9FDAFD"

# CYAN
COLOR_CYAN_DARK="#7ecefd"
COLOR_CYAN_LIGHT="#9FDAFD"

# WHITE
COLOR_WHITE_DARK="#FFF6E5"
COLOR_WHITE_LIGHT="#FFFDFA"
